#!/usr/bin/env bash

# configures nginx to run and listen to port 80.

sudo -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
